### ISSUE TITLE
Privacy Violation

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/tcf#8]
We found a problem about Privacy Violation in tcf-master/tcfl/ttb_client.py
![image](https://user-images.githubusercontent.com/39950310/60332109-b6268f00-99c8-11e9-8d5c-173db6338b6e.png)
Mishandling private information, can compromise user privacy and is often illegal.Privacy is a priority when privacy conflicts with other issues.

**Comment by inakypg** [comment]
You might want to provide more info here...

**Comment by inaky-intc** [comment]
No more info provided, cclosing
